Develop
telosnetwork/app-telos-native pull request #104
Opened 2022-09-21 17:28 UTC by donnyquixotic

Fixes #90 #97

2022-09-21 18:03 UTC, donnyquixotic commented
in addition to deploy links, see https://app-stage.telos.net/

2022-09-22 10:04 UTC, Kersten-TCD requested changes
- Dialogue for users that are not part of proposal DAO (Group) missing
- Error message for user that is not part of a DAO (group) is still cryptic in transaction protocol "Cast a vote TypeError: Cannot read properties of undefined (reading 'details')", interface error message "Error Signing Transaction"
- Vote will increase vote count but list of voting accounts is not updated. Only 20 of 36 voters shown in proposal details
- Welcome text for account is not final version
- Create Poll button on main page to be removed for this Version
- Create a treasury modal "cancel" button has no function leaves user locked until refresh

- Function "create treasury" tested on testnet remains in anchor request status "Loading Preparing Request", seems broken, remove for now

![Bildschirmfoto 2022-09-22 um 12 16 48](https://user-images.githubusercontent.com/39388424/191721693-47fbeeca-e2c6-42f5-bbb4-c6046edc1f59.png)

![Bildschirmfoto 2022-09-22 um 12 13 50](https://user-images.githubusercontent.com/39388424/191721038-1b50ee2c-ed8d-4ad2-b2f5-3afda0d0cde3.png)

Backlog Item
- Renaming of "Create Treasury" to "Create a DAO" for next release

Filters are working as expected, same for general voting, landing page removed which is now much cleaner.

2022-09-25 21:10 UTC, Kersten-TCD approved these changes

2022-09-25 21:28 UTC, karynemayer approved these changes

2022-09-25 22:16 UTC, merged