Better showing the Voted status of ballot on BallotView
telosnetwork/app-telos-native pull request #168
Opened 2022-10-03 22:33 UTC by Viterbo

# Description
Better showing the Voted status of a ballot on BallotView

Fixes #163

## Changes
- Included the two new icons: voted-icon.svg and voted-icon-black.svg
- Change to black and white the status of an ended ballot on BallotView
- Adding a top-left chip showing the Voted status 

## Screenshots
![image](https://user-images.githubusercontent.com/4420760/193697655-24b711b3-05ec-4276-9c86-78cc0b3b9ac3.png)

2022-10-04 05:21 UTC, karynemayer requested changes
The previous voted indication is still being used 
<img width="1418" alt="Screen Shot 2022-10-03 at 22 20 56" src="https://user-images.githubusercontent.com/2939354/193740536-025f01ea-f7eb-422b-93bd-4912e6db9375.png">

2022-10-06 23:34 UTC, donnyquixotic requested changes

2022-10-06 23:34 UTC, donnyquixotic commented on src/pages/trails/ballots/components/BallotChip.vue
> +  background: #00A402
move hex to gobal css variable to keep track of the colors we're using throughout the app

2022-10-06 23:34 UTC, donnyquixotic commented on src/pages/trails/ballots/components/BallotChip.vue
>    background: #FFB010
move hex to gobal css variable to keep track of the colors we're using throughout the app

2022-10-07 14:41 UTC, donnyquixotic approved these changes

2022-10-10 14:02 UTC, merged