return links in menu and dropdown menu
telosnetwork/app-telos-native pull request #173
Opened 2022-10-05 15:40 UTC by DevArtemNuss

# Description

Fixes #142 
Returned links 
## Changes

List the changes made to achieve the feature or fix the bug.

-   Return link in header-menu
-   Return link in dropdown-menu

## Screenshots

Add screenshots that show your changes
<img width="800" alt="Снимок экрана 2022-10-05 в 17 39 30" src="https://user-images.githubusercontent.com/92740446/194102560-cf67f00b-6641-4ec5-b201-fbde13443ba4.png">

# Checklist:

-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings
-   [ ] I have executed manual tests that prove my fix is effective or that my feature works

2022-10-06 16:26 UTC, karynemayer requested changes
The idea is to enable the profile page (as a working page) accessible only through the url, without the edit profile button.

Apologies for the issue not being clear

2022-10-06 20:46 UTC, Viterbo approved these changes

2022-10-06 23:25 UTC, donnyquixotic approved these changes

2022-10-07 03:32 UTC, karynemayer commented
I'm going to close this PR because it doesn't have any relevant changes and pr https://github.com/telosnetwork/app-telos-native/pull/175 fixes this.

2022-10-07 03:32 UTC, closed without merging