return profile info
telosnetwork/app-telos-native pull request #175
Opened 2022-10-06 13:18 UTC by DevArtemNuss

# Description

Fixes #140 
Include a summary of your changes.

## Changes

List the changes made to achieve the feature or fix the bug.

-   Add conditions 

## Screenshots
<img width="706" alt="Снимок экрана 2022-10-06 в 15 18 09" src="https://user-images.githubusercontent.com/92740446/194323115-fb24dfec-9294-4d58-9b13-817b98375bec.png">

Add screenshots that show your changes

# How Has This Been Tested?

Go to path Profile and make some edits with them

# Checklist:

-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings
-   [ ] I have executed manual tests that prove my fix is effective or that my feature works

2022-10-06 20:40 UTC, Viterbo requested changes
I added 3 minor change suggestions to remove unnecessary code.

2022-10-06 20:40 UTC, Viterbo commented on src/pages/profiles/ProfileAvatar.vue
> +  }
I would suggest removing the whole function until is needed again.

```suggestion
```

2022-10-06 20:40 UTC, Viterbo commented on src/store/profiles/actions.js
> +  //await getProfile({ commit })
This should be removed instead of commented to avoid accumulating non-necessary code.

```suggestion
```

2022-10-06 20:40 UTC, Viterbo commented on src/store/profiles/actions.js
> +  console.log(this.state.profiles)
cleaning up forgotten console logs
```suggestion
```

2022-10-07 03:34 UTC, karynemayer approved these changes
👍🏻 to merge after Viter's comments are addressed

2022-10-07 12:19 UTC, Viterbo approved these changes

2022-10-10 00:04 UTC, merged