Feat/show profile
telosnetwork/app-telos-native pull request #180
Opened 2022-10-11 14:24 UTC by DevArtemNuss

# Description

Fixes #179

## Changes

List the changes made to achieve the feature or fix the bug.

-   Return Profile Page
-   Return Edit Profile Page 
-   Change paths 
-   Add link in menu
-   Add 'Go back' button
## Screenshots

Add screenshots that show your changes
<img width="400" alt="Снимок экрана 2022-10-11 в 16 23 30" src="https://user-images.githubusercontent.com/92740446/195117822-4e629912-d118-4c34-b81e-a1d9878c0a0e.png">
<img width="1263" alt="Снимок экрана 2022-10-11 в 16 23 43" src="https://user-images.githubusercontent.com/92740446/195117858-a28b9b3f-ec7f-44b6-a478-130eb40e8795.png">
<img width="1438" alt="Снимок экрана 2022-10-11 в 16 23 53" src="https://user-images.githubusercontent.com/92740446/195117913-437e693c-b8f3-4c7a-a1af-06fc56bc6a06.png">

# How Has This Been Tested?

Open menu and use it 

# Checklist:

-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings
-   [ ] I have executed manual tests that prove my fix is effective or that my feature works

2022-10-11 15:56 UTC, donnyquixotic approved these changes

2022-10-13 14:21 UTC, Viterbo requested changes

2022-10-15 19:46 UTC, donnyquixotic commented on src/router/routes.js
>      component: () => import("pages/profiles/read/MyProfile.vue"),
@Viterbo is this resolved? seems to still reference the `MyProfile` component when referencing routes with `:id`

2022-10-15 19:52 UTC, donnyquixotic commented
@DevArtemNuss can you complete the checklist in the description?

2022-10-17 10:27 UTC, DevArtemNuss commented
@donnyquixotic Done

2022-10-19 04:07 UTC, merged