v1.0.1-rc
telosnetwork/app-telos-native pull request #227
Opened 2022-11-08 21:04 UTC by karynemayer

## Description
This PR represented the v1.0.1 release candidate.

2022-11-08 21:33 UTC, donnyquixotic approved these changes

2022-11-10 04:21 UTC, karynemayer commented
@Kersten-TCD, if you haven't started testing yet, I recommend we merge https://github.com/telosnetwork/app-telos-native/pull/216 before. If you already started, we can leave it to the next release

2022-11-10 15:40 UTC, Kersten-TCD requested changes
Full end 2 end test. Chrome on MACOS Ventura:

- Login with Anchor **pass**
- Logout **pass**
- Open transaction history, show past transactions or messages (local storage?) **pass**
- Show welcome message at first login **pass**
- Open Proposals and show all active for Vote DAO (Telos Governance) **pass**
- Create a poll button visible **improvement** please rename to "Create a proposal"
- "Dynamic" Button for proposals based on voting status of account, "View proposal & vote" for unvoiced proposals, "View Proposal / 
![Bildschirm­foto 2022-11-10 um 15 56 20](https://user-images.githubusercontent.com/39388424/201126481-e918b49f-1ed9-41dc-9284-3f17eab92a76.png)
update vote" for untouched proposals **pass**
- Select "Elections" in top menu opens Elections page / changes filters **fail** minor bug, manual refresh required
- Return to "Proposals" in top menu opens proposals page / changes filters **fail** minor bug, manual refresh required
- Select "DAOs" in top menu opens DAO page **pass**
- Return to "Proposals" in top menu opens proposals page **pass**
- Reactive Design of landing page **pass**

Filters and Proposal presentation:

- Selection of a DAO in filter updates page with relevant entries **pass**
- Selection of a DAO in filter updates page with relevant entries after confirmation **improvement** update displayed proposals when selection status option
- Selection of Type in filter updates page with relevant entries **improvement** update displayed proposals when selection status option
- Sort by all available options in filter, verify results are changed accordingly **pass**
- Toggle list view and gallery view changes appearance of proposals **pass*
- Test all Filter options based on list view **pass**
- Filters keep settings at refresh **improvement** Filters are reset to default when refreshing the page

Voting:

- Open Proposal **pass**
- Display proposal Image, if available **pass** @Viterbo please verify if Image is shown if no PDF is attached for Ballot creation Wizard - should show PDF or nothing if only image attached
- Proposal popup size and display **improvement** please verify increas of size for popup, since it looks very compressed. Reactive design to be considered.
- Reactive design off proposal popup **pass**
- Vote button remains inactive until selection was made **pass**
- Percentage of cast vote, Number of Accounts and Tokens updates immediately **pass**
- Click on "Number of Accounts" opens voter details. Percentage and voted account list updates immediately **pass**
- Display all accounts that have voted in "Number of Accounts" details **not tested" not enough voters to verify. Past release only showed 20 voters.
- Change of vote updates all of the above information **pass**
- Vote button of proposal changes in proposal overview after voting "View proposal / update vote" **pass"

Proposal creation:

- Ballot Main Info **improvement** please rename to "Proposal Details"
- Image URL will display preview **pass**
- Upload PDF opens explorer/finder window to select file. File can be selected **pass**
- Telos Community is set to default DAO **pass**
- Custom DAO dropdown only shows joined DAOs **pass**
- Join New DAO button opens DAO page **improvement** All changes are discarded when leaving the Proposal creation dialogue, consider to add possibility to save proposal draft in local storage
- **improvement** Please check wording for "Allow users voting using" = "Allow users to vote with:" and verify "Only stakeable tokens" should this be "Only staked tokens"? 
- Select all voting options and verify correct behavior **improvement** For "Multiple option(s)" please correct spelling, also Default text should be removed or selected when selecting one of the options to allow easy addition of new option, while keeping the possibility to correct spelling errors.
![Bildschirm­foto 2022-11-10 um 15 56 20](https://user-images.githubusercontent.com/39388424/201126481-e918b49f-1ed9-41dc-9284-3f17eab92a76.png)
- **improvement** Please change text to "Multiple option ballots are entirely configurable. You can define several options, and voters may select one or multiple choices depending on the configuration."
- Open Voting set to default "Right away" **pass**
- **improvement** Please consider text change "You can open this proposal for voting now or activate it later. (Smart Contract interaction needed)" & "Open for voting now"
- Create Ballot **improvement** please rename to "Create Proposal" and update capital letters in preview.
![Bildschirm­foto 2022-11-10 um 16 12 29](https://user-images.githubusercontent.com/39388424/201132933-c35f578d-12f3-4d37-b9db-3f0f8af4fcb2.png)
- Reactive design off proposal creation dialogue **pass** 
- Creation of proposal and preview opened **verification needed** proposal created but PDF file is not displayed, image is shown instead. second test uploaded PDF correctly. Please verify function.
- Created proposals are shown in list of active proposals **fail** blocker, proposals need to be shown. Please verify https://explorer-test.telos.net/transaction/9e5864bc75117821abd301ca2fefa62b814872278300bf35d1e5c53f5c599c06 and https://explorer-test.telos.net/transaction/4c272226fa50db3164241a2ad9215a0670975d0796365a3e3554f9374703e387
![Bildschirm­foto 2022-11-10 um 16 24 21](https://user-images.githubusercontent.com/39388424/201136828-afea0b04-e2fa-4607-b180-c7a602b815e2.png)

DAO page

- Status of logged in account is correctly displayed for each DAO **fail** does not update based on status for user that has actively voted. Minor bug.
- Create a DAO feature **not tested** please see #229 for initial comments

Set to request changes due to issue with newly created proposals not showing on page, and unexpected drop of PDF file during proposal creation (might be user error though). Please verify.

2022-11-10 15:44 UTC, Kersten-TCD commented
@karynemayer @Viterbo @donnyquixotic I have performed a full feature test (except DAO creation). I have found a blocker, since newly created proposals are not shown, even though start date is set to "now". The proposal is shown directly after creation, but can not be searched / shown on the page. 

Please also test PDF attachment, since the document was dropped once. It could be user error of myself. Second test worked and displayed the PDF.

Various other improvements are mentioned, please handle as we did for the OBE release.

2022-11-17 00:51 UTC, merged