saving ballot creation state and recover from localStore
telosnetwork/app-telos-native pull request #254
Opened 2022-11-18 04:07 UTC by Viterbo

# Fixes #241

## Description
While creating a ballot the user may decide to cancel the process and come back later. If the user leaves the form now he or she is asked whether to save the draft or discard the changes.

## screenshots
![image](https://user-images.githubusercontent.com/4420760/202614471-df1a2fce-ed20-4e50-a38c-dc1875b45272.png)

2022-11-18 04:40 UTC, donnyquixotic requested changes

2022-11-18 04:40 UTC, donnyquixotic commented on src/pages/trails/ballots/components/BallotForm.vue
> +            //     });
remove commented code

2022-11-18 05:43 UTC, Viterbo commented on src/pages/trails/ballots/components/BallotForm.vue
> +            //     });
done here [99ef224](https://github.com/telosnetwork/app-telos-native/pull/254/commits/99ef224f4bdf5696871bf83fcb58f90be232d887)

2022-11-19 21:07 UTC, donnyquixotic approved these changes

2022-11-21 22:37 UTC, karynemayer approved these changes

2022-11-21 22:38 UTC, merged